KS-1-5 add new variables and print in console
MaxPirojkov/KotlinSprint1 pull request #5
Opened 2024-06-09 21:12 UTC by MaxPirojkov

2024-06-10 07:39 UTC, ievetrovdev requested changes

2024-06-10 07:39 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson_1_Task_5.kt
> +    val hour: Float = sumOfSecondsInSpace / 3600F
Чтобы снизить риск ошибок, предлагаю все “голые” числа вынести в константу. Кроме того это [магические числа](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F), что тоже не является хорошей практикой.

2024-06-10 07:39 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson_1_Task_5.kt
> +    println("${hour.toInt()}:${minute.toInt()}:$seconds")
Для правильного вывода попробуй String.format

2024-06-10 07:39 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson_1_Task_5.kt
> +    val minute = (hour - 1) * 60
Сейчас у тебя не правильно считается значение. Умножения можно избежать, попробуй использовать только деление и деление без остатка (/ и %)

2024-06-10 12:18 UTC, MaxPirojkov commented on src/main/kotlin/lesson_1/lesson_1_Task_5.kt
> +    val hour: Float = sumOfSecondsInSpace / 3600F
спасибо за ревью. поправил

2024-06-10 12:18 UTC, MaxPirojkov commented on src/main/kotlin/lesson_1/lesson_1_Task_5.kt
> +    println("${hour.toInt()}:${minute.toInt()}:$seconds")
добавил String.format

2024-06-10 12:18 UTC, MaxPirojkov commented on src/main/kotlin/lesson_1/lesson_1_Task_5.kt
> +    val minute = (hour - 1) * 60
поменял на (/ и %)

2024-06-10 12:59 UTC, ievetrovdev requested changes

2024-06-10 12:59 UTC, ievetrovdev commented on src/main/kotlin/lesson_1/lesson_1_Task_5.kt
> +const val oneHourInSeconds = 3600
Нейминг констант отличен от обычных переменных. В [документации по ссылке](https://developer.android.com/kotlin/style-guide#constant_names) есть более полное описание стайл гайда
3600 это константа верно, а 6480 в данном случае не константа, так как число может меняться и это не скажется на работе программы (может захотеть другое число посчитать). Про 60 же почему то забыл, хотя оно всегда будет одинаковым.

2024-06-11 07:33 UTC, ievetrovdev approved these changes
Отлично

2024-06-11 16:17 UTC, merged